@startuml
'https://plantuml.com/object-diagram
object ResourcesToAdd {
 Redstone
 Diamond (from coal?)
 Lapis Lazuli
 Emerald
}

'Objects
' Fluids
object Lava
object Water
object Chocolate

' Blocks
object Cobblestone {
    Lava from side
}
object Andesite {
    Lava from above
}
object ScoriaCobblestone
object NaturalScoria
object Scoria
object DarkScoria {
    Black Dye
}
object Gravel
object Sand
object LimeSand
object Limestone
object WeatheredLimestone
object Dirt
object SoulSand

' Plants
object OakTree
object Wood
object Sapling
object Wheat
object Bonemeal
object Charcoal
object Kelp
object JungleLeaves
object CocoaBeans

' Mobs
object Egg
object Milk

' Minerals
object Iron
object Clay
object NetherQuartz
object Gold
object Zinc
object Copper

' Misc
object CalamineMix
object RawCalamine
object Malachite
object SawDust
object WoodPulp
object Cardstock {
 Mob drops
}

' Machine
diamond Mixer

'Arrows

' Blocks from Fluids and other misc interactions
Lava .. Cobblestone
Water .. Cobblestone
Lava .. Andesite
Water .. Andesite
Lava .. ScoriaCobblestone
Chocolate .. ScoriaCobblestone

OakTree ...... Wood
OakTree .. Sapling
OakTree .. JungleLeaves : ???
Bonemeal .. Wheat : Grass
Bonemeal .. Kelp : Seagrass
WoodPulp .. Cardstock : Press

Egg .. Mixer
Milk .. Mixer
CocoaBeans .. Mixer
Mixer .. Chocolate : Mixer

' Milling --*
Cobblestone --* Gravel
Gravel --* Sand
Sand --* LimeSand
Limestone --* RawCalamine
LimeSand --* Bonemeal
DarkScoria --* SoulSand
Wood --* SawDust
JungleLeaves --* CocoaBeans
WeatheredLimestone --* Malachite

' Washing --|>
Gravel --|> Iron
Sand --|> Clay
SoulSand --|> NetherQuartz
SoulSand --|> Gold
SawDust --|> WoodPulp
Limestone --|> WeatheredLimestone


' Smelting --o
Wood --o Charcoal
ScoriaCobblestone --o NaturalScoria
NaturalScoria --o Scoria
LimeSand --o Limestone
CalamineMix --o Zinc
Malachite --o Copper


' Crafting -->
Scoria --> DarkScoria
Charcoal --> CalamineMix
RawCalamine --> CalamineMix
Wheat --> Dirt
Sapling --> Dirt

hide empty attributes

@enduml
