@startuml
'https://plantuml.com/object-diagram

' Fluids
object Water
object Chocolate


' Blocks from Fluids
object Cobblestone
object Andesite
object ScoriaCobblestone

Water .. Cobblestone : Lava\nfrom side
Water .. Andesite : Lava\nfrom above
Chocolate .. ScoriaCobblestone : Lava


' Milling --*
object Gravel
object Sand
object LimeSand
object Bonemeal
object RawCalamine

Cobblestone --* Gravel
Gravel --* Sand
Sand --* LimeSand
Limestone --* RawCalamine


' Washing --|>
object Iron
object Clay

LimeSand --* Bonemeal : [7%]
Gravel --|> Iron : [12%]
Sand --|> Clay : [25%]


' Smelting --o
object NaturalScoria
object Scoria
object Limestone

ScoriaCobblestone --o NaturalScoria
NaturalScoria --o Scoria
LimeSand --o Limestone


' Crafting ..|>
object DarkScoria {
    Made with Black Dye
}

Scoria ..|> DarkScoria
@enduml
